name: blanket # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo
adopt-info: blanket
platforms:
  amd64:
  arm64:
  armhf:
parts:
  blanket:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://github.com/rafaelmardojai/blanket.git
    source-tag: '0.7.0'
    source-depth: 1
    meson-parameters:
      - --prefix=/snap/blanket/current/usr
    parse-info: [usr/share/metainfo/com.rafaelmardojai.Blanket.metainfo.xml]
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/blanket/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
      sed -e '1c#!/usr/bin/env python3' -i $CRAFT_PART_INSTALL/snap/blanket/current/usr/bin/blanket
    organize:
      snap/blanket/current: .

  gpu-2404:
    after: [blanket]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
    - -*

  deps:
    plugin: nil
    stage-packages:
      - libgstreamer-plugins-bad1.0-0
      - gir1.2-gstreamer-1.0
      - gir1.2-gst-plugins-bad-1.0
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - blanket
      - deps
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - gtk-common-themes
      - gnome-46-2404
      - core24
      - blueprint-compiler

slots:
  blanket-mpris:
    interface: mpris
    name: Blanket
  blanket:
    interface: dbus
    bus: session
    name: com.rafaelmardojai.Blanket

apps:
  blanket:
    command: usr/bin/blanket
    extensions: [gnome]
    common-id: com.rafaelmardojai.Blanket
    plugs:
      - audio-playback
